# Project information
site_name: Sample Docs
site_url: https://patrick-5546.github.io/sampleproject/
site_author: A. Random Developer
site_description: >-
  Documentation site for sample, a sample Python project

# Repository
repo_name: patrick-5546/sampleproject
repo_url: https://github.com/patrick-5546/sampleproject
edit_uri: "edit/main/docs/"

# Configuration
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - git-revision-date-localized:
      timezone: America/Vancouver
  - offline
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

# Customization
extra:
  social:
    - icon: material/github
      link: https://github.com/patrick-5546
    - icon: material/email
      link: mailto:author@example.com

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home:
    - index.md
    - License: license.md
  - User Guide:
    - Installation: user_guide/installation.md
    - Getting Started: user_guide/getting_started.md
    - Commands: user_guide/commands.md
    - Configuration: user_guide/configuration.md
  - Developer Guide:
    - Contributing: developer_guide/contributing.md
    - Releases: developer_guide/releases.md
    - GitHub Actions Integration: developer_guide/github_actions.md
    - VS Code Integration: developer_guide/vscode.md

# Live reloading for paths other than 'docs' and 'mkdocs.yml'
watch:
- LICENSE
- README.md
